id: I2F2D36B2
default_language: zh
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:28.425213
last_modified: 2023-01-04 11:29:28.425220
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  E021:
    title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
    base_file: E021.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
